language: java

sudo: false
addons:
  apt:
    packages:
      #- oracle-java8-installer
      - oracle-java7-installer

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6

before_script:
  - mvn test -B
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - jdk_switcher use oraclejdk8
  - # do stuff with Java 8
  - jdk_switcher use oraclejdk7
  - # do stuff with Java 7

